# Generated by Django 4.1.7 on 2023-02-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=64)),
                ('project_type', models.CharField(max_length=64)),
                ('client_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
